services:
  app-environment:
    container_name: app
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8889:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cpe123456
      MYSQL_DATABASE: university
    ports:
      - "3306:3306"
    volumes:
      - "./university.sql:/docker-entrypoint-initdb.d/1.sql"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db